// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0701N6139UARmLJ17U0DaMyx8PRqzI0I',
    appId: '1:568943595835:web:af11a7cb208ed1ffb7671e',
    messagingSenderId: '568943595835',
    projectId: 'habit-tracker-011',
    authDomain: 'habit-tracker-011.firebaseapp.com',
    storageBucket: 'habit-tracker-011.firebasestorage.app',
    measurementId: 'G-XDS5R53SV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAdHtsDV8pNd1HkhuuIWk8akyjSrftyic',
    appId: '1:568943595835:android:95187bca06d9bcb1b7671e',
    messagingSenderId: '568943595835',
    projectId: 'habit-tracker-011',
    storageBucket: 'habit-tracker-011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFJ5UduooeJcmyUdS2R3auh5YQWHcfk0',
    appId: '1:568943595835:ios:6f225083e8629d45b7671e',
    messagingSenderId: '568943595835',
    projectId: 'habit-tracker-011',
    storageBucket: 'habit-tracker-011.firebasestorage.app',
    iosClientId: '568943595835-lafsfibh54pf0gk936v2k6la6r5affuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFJ5UduooeJcmyUdS2R3auh5YQWHcfk0',
    appId: '1:568943595835:ios:6f225083e8629d45b7671e',
    messagingSenderId: '568943595835',
    projectId: 'habit-tracker-011',
    storageBucket: 'habit-tracker-011.firebasestorage.app',
    iosClientId: '568943595835-lafsfibh54pf0gk936v2k6la6r5affuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0701N6139UARmLJ17U0DaMyx8PRqzI0I',
    appId: '1:568943595835:web:083015bc74235dc2b7671e',
    messagingSenderId: '568943595835',
    projectId: 'habit-tracker-011',
    authDomain: 'habit-tracker-011.firebaseapp.com',
    storageBucket: 'habit-tracker-011.firebasestorage.app',
    measurementId: 'G-RQB86DP82D',
  );
}
